spring.application.name=LIAProjekt

# ===== ENV VARIABLES =====
spring.cloud.azure.tenant-id=${TENANT_ID}
spring.cloud.azure.credential.client-id=${CLIENT_ID}
spring.cloud.azure.credential.client-secret=${CLIENT_SECRET}

# ===== GRAPH =====
graph.base-url=https://graph.microsoft.com/v1.0
graph.scope=https://graph.microsoft.com/.default

# ===== JWT VALIDATION (FRONTEND TOKENS) =====
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/${TENANT_ID}/
spring.security.oauth2.resourceserver.jwt.audiences=api://${CLIENT_ID}

# V2 format måste ändras i azure portal om vi vill använda
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${TENANT_ID}/v2.0
