spring.application.name=LIAProjekt

# ===== ENV VARIABLES =====
spring.cloud.azure.tenant-id=${TENANT-ID}
spring.cloud.azure.credential.client-id=${CLIENT-ID}
spring.cloud.azure.credential.client-secret=${CLIENT-SECRET}

spring.cloud.azure.keyvault.secret.endpoint=https://kv-app-dev01.vault.azure.net/
spring.cloud.azure.keyvault.secret.enabled=true

# ===== GRAPH =====
graph.base-url=https://graph.microsoft.com/v1.0
graph.scope=https://graph.microsoft.com/.default

# ===== JWT VALIDATION (FRONTEND TOKENS) =====
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/${TENANT-ID}/
#spring.security.oauth2.resourceserver.jwt.audiences=api://${CLIENT_ID}

# V2 format måste ändras i azure portal om vi vill använda
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${TENANT_ID}/v2.0

# ===== DATABASE CONFIG =====
#CHANGE THIS TO MATCH PROPER DATABASE
spring.datasource.url=jdbc:h2:mem:test_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update