spring.application.name=LIAProjekt

# ===== ENV VARIABLES =====


# ==== KEY VAULT =====
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://kv-app-dev01.vault.azure.net/
spring.cloud.azure.keyvault.secret.property-sources[0].credential.managed-identity-enabled=true

# ===== BLOB STORAGE =====
spring.cloud.azure.storage.blob.account-name=${AZURE_STORAGE_ACCOUNT_NAME}
spring.cloud.azure.storage.account-key=${AZURE_STORAGE_ACCOUNT_KEY}
spring.cloud.azure.storage.container-name-pdf=${AZURE_STORAGE_CONTAINER_NAME_PDF}
spring.cloud.azure.storage.container-name-video=${AZURE_STORAGE_CONTAINER_NAME_VIDEO}
spring.cloud.azure.storage.sas-expiry-minutes=60
spring.cloud.azure.storage.frontdoor-endpoint=${AZURE_STORAGE_FRONTDOOR_ENDPOINT}

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


# ===== GRAPH =====
graph.base-url=https://graph.microsoft.com/v1.0
graph.scope=https://graph.microsoft.com/.default

# ===== JWT VALIDATION (FRONTEND TOKENS) =====
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/${AZURE_TENANT_ID}/

# ===== DATABASE CONFIG =====
#CHANGE THIS TO MATCH PROPER DATABASE
spring.datasource.url=jdbc:h2:mem:test_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Mail sender
azure.graph.mail-user=no-reply@CampusMolndal.onmicrosoft.com


# ====================
# LOCAL TESTING
# ====================

# Enable/disable outgoing emails with true/false
app.email.enabled=false

# Allow anonymous users during local testing
app.allow-anonymous-events=false

# ===== DEV DATABASE SEEDER FOR LOCAL TESTS =====
#spring.profiles.active=dev

test.properties=false