name: Deploy to Azure

on:
  push:
    branches:
      - main  # Körs när kod pushas till main-grenen

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Setup Java 21 för backend och specifika distribution (t.ex. zulu)
    - name: Set up Java 21 (Zulu)
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'zulu'  # Specificera distribution (ex. zulu, adoptopenjdk)

    # Cache Maven dependencies för backend
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Bygg backend med Maven (i rätt mapp)
    - name: Build backend with Maven
      run: mvn clean install -DskipTests=true
      working-directory: ./Backend  # Kör i backend-mappen

    # Lista de byggda artefakter (t.ex. JAR-fil) efter Maven-build
    - name: List built artifacts
      run: ls -l ./Backend/target  # Detta listar alla filer i target-mappen i backend-mappen, inklusive den genererade JAR-filen

    # Deploy backend till Azure
    - name: Deploy backend to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: app-dev-api  # Backend App Service
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
        package: ./Backend/target/*.jar  # Vägen till JAR-filen i backendens target-mapp

  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Setup Node.js 20 för frontend
    - name: Set up Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    # Cache Node.js beroenden för frontend
    - name: Cache Node.js dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Installera frontend-beroenden (i rätt mapp)
    - name: Install frontend dependencies
      run: npm install
      working-directory: ./Frontend  # Kör i frontend-mappen

    # Bygg frontend (i rätt mapp)
    - name: Build frontend
      run: npm run build
      working-directory: ./Frontend  # Kör i frontend-mappen

    # Deploy frontend till Azure
    - name: Deploy frontend to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: app-dev-web  # Frontend App Service
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}
        package: ./Frontend/dist  # Vägen till byggmappen för frontend (dist)